# Pandas Python Library

Pandas is an open-source Python library built on top of NumPy that provides fast, flexible, and expressive data structures designed for data manipulation, cleaning, and analysis.

In [4]:
import pandas as pd
import numpy as np

The Pandas library relies on two primary data structures: the Series and the DataFrame .
*  Series is a one-dimensional, labeled array capable of holding any data type
* A DataFrame is a two-dimensional, tabular data structure with labeled axes (rows and columns).

## Series
A Series consists of two parts:
* Data – Stores the actual values (can be any NumPy data type).
* Index – Stores labels for each data value.
Each value in the data array is associated with a corresponding label in the index array.
The index makes it easy to identify and access individual elements
* The Series constructor is used to create a Pandas Series.
* By default, pandas will assign numerical values increasing from 0 as labels.

In [5]:
s = pd.Series([12,-4,7,9])
s

0    12
1    -4
2     7
3     9
dtype: int64

In [6]:
s = pd.Series([12,-4,7,9] , index = ['a','b','c','d'])
s

a    12
b    -4
c     7
d     9
dtype: int64

The two arrays that make up a Pandas Series are:

1. Data Array
* Stores the actual values of the Series.
* Can contain any NumPy-supported data type (integers, floats, strings, etc.).
2. Index Array
* Stores the labels (indexes) for each data value.
* Each label uniquely identifies the corresponding element in the data array.

In [7]:
s.values

array([12, -4,  7,  9])

In [8]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [9]:
s['a']

np.int64(12)

In [10]:
s[0:2]

a    12
b    -4
dtype: int64

In [11]:
s['a':'c']

a    12
b    -4
c     7
dtype: int64

In [12]:
s[['b','c']]

b   -4
c    7
dtype: int64

In [13]:
s['c'] = 0

In [14]:
s

a    12
b    -4
c     0
d     9
dtype: int64

In [15]:
array1 = np.array([1,2,3,4])
s2 = pd.Series(array1 , index = ['a','b','c','d'])
s2

a    1
b    2
c    3
d    4
dtype: int64

In [16]:
s3 = pd.Series(s)
s3

a    12
b    -4
c     0
d     9
dtype: int64

In [17]:
s2

a    1
b    2
c    3
d    4
dtype: int64

* the values contained in the NumPy array or in the original series are not copied, but are passed by reference.

In [18]:
array1[2] = -2
array1

array([ 1,  2, -2,  4])

In [19]:
s2

a    1
b    2
c    3
d    4
dtype: int64

### Filtering Values
* The NumPy library is the base of the pandas library and, for its
data structures, many operations that are applicable to NumPy arrays are
extended to the series.

In [20]:
s[s<8]

b   -4
c    0
dtype: int64

In [21]:
s/2

a    6.0
b   -2.0
c    0.0
d    4.5
dtype: float64

In [22]:
np.log(s)

c:\Users\Shreya Deshmukh\OneDrive\Desktop\Advance Datascience\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\Shreya Deshmukh\OneDrive\Desktop\Advance Datascience\.venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

a    2.484907
b         NaN
c        -inf
d    2.197225
dtype: float64

### Evaluating Values

In [23]:
import pandas as pd

serd = pd.Series(
    [1, 0, 2, 1, 2, 3],
    index=['white', 'white', 'blue', 'green', 'green', 'yellow']
)

print(serd)

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

In [24]:
serd.unique

<bound method Series.unique of white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64>

In [25]:
serd.value_counts()

1    2
2    2
0    1
3    1
Name: count, dtype: int64

In [26]:
serd.isin([0,3])

white     False
white      True
blue      False
green     False
green     False
yellow     True
dtype: bool

In [27]:
serd[serd.isin([0,3])]

white     0
yellow    3
dtype: int64

In [28]:
s2 = pd.Series([5,-3,np.nan,14])
s2

0     5.0
1    -3.0
2     NaN
3    14.0
dtype: float64

* NaN stands for Not a Number. It is a special value used to represent missing or undefined data.
* Because NaN (Not a Number) is a floating-point value, pandas converts the entire Series to float64.

* isnull() :
Checks whether each value is missing (NaN).
* notnull() :
Checks whether each value is not missing.

In [29]:
s2.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [30]:
s2.notnull()

0     True
1     True
2    False
3     True
dtype: bool

In [31]:
s2[s2.notnull()]

0     5.0
1    -3.0
3    14.0
dtype: float64

In [32]:
s2[s2.isnull()]

2   NaN
dtype: float64

In [33]:
mydict = {'red' : 2000 , 'blue' : 1000 , 'yellow' : 500 , 'orange' : 1000}
myseries = pd.Series(mydict)
myseries

red       2000
blue      1000
yellow     500
orange    1000
dtype: int64

In [34]:
mydict2 = {'red' : 400 , 'yellow' : 100 , 'black' : 700}
myseries2 = pd.Series(mydict2)
myseries + myseries2

black        NaN
blue         NaN
orange       NaN
red       2400.0
yellow     600.0
dtype: float64

* When adding two Series, pandas aligns them by their index labels, not by their positions.
* red: 2000 + 400 = 2400
* yellow: 500 + 100 = 600
* blue: No matching value in myseries2 → NaN
* orange: No matching value in myseries2 → NaN
* black: No matching value in myseries → NaN

In [35]:
import pandas as pd

mydict = {
    'red': 'Apple',
    'blue': 'Sky',
    'yellow': 'Sun',
    'orange': 'Mango'
}

myseries = pd.Series(mydict)

mydict2 = {
    'red': ' Juice',
    'yellow': ' Flower',
    'black': 'Night'
}

myseries2 = pd.Series(mydict2)

print(myseries)
print(myseries2)

print(myseries + myseries2)

red       Apple
blue        Sky
yellow      Sun
orange    Mango
dtype: str
red         Juice
yellow     Flower
black       Night
dtype: str
black             NaN
blue              NaN
orange            NaN
red       Apple Juice
yellow     Sun Flower
dtype: str

### DataFrame

* A DataFrame is a two-dimensional, size-mutable, and heterogeneous tabular data structure with labeled rows (index) and columns. It is similar to an Excel spreadsheet or a SQL table.

In [36]:

data = {'color' : ['blue','green','yellow','red','white'],
'object' : ['ball', 'pen','pencil', 'paper','mug'],
'price' : [1.2,1.0,0.6,0.9,1.7]}

frame = pd.DataFrame(data)
frame

    color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [37]:
frame2 = pd.DataFrame(data,columns=['objects','price'])
frame2

  objects  price
0     NaN    1.2
1     NaN    1.0
2     NaN    0.6
3     NaN    0.9
4     NaN    1.7

In [38]:
frame2 = pd.DataFrame(data,index = ['one','two','three','four','five'])
frame2

        color  object  price
one      blue    ball    1.2
two     green     pen    1.0
three  yellow  pencil    0.6
four      red   paper    0.9
five    white     mug    1.7

The DataFrame constructor accepts three main arguments:

1. data
* Contains the actual data.
* It can be a dictionary, list, tuple, NumPy array, or another DataFrame.
2. index
* Contains the labels for the rows.
* If not specified, pandas assigns default row numbers (0, 1, 2, ...).
3. columns
* Contains the names (labels) of the columns.
* If not specified, pandas assigns default column names.

In [39]:
frame3 = pd.DataFrame(np.arange(16).reshape((4,4)),
index = ['red','blue','yellow','white'],
columns = ['ball','pen','pencil','paper'])

frame3

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

### Selecting Elements

In [40]:
frame

    color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [41]:
frame.columns

Index(['color', 'object', 'price'], dtype='str')

In [42]:
frame.index

RangeIndex(start=0, stop=5, step=1)

In [43]:
frame.values

array([['blue', 'ball', 1.2],
       ['green', 'pen', 1.0],
       ['yellow', 'pencil', 0.6],
       ['red', 'paper', 0.9],
       ['white', 'mug', 1.7]], dtype=object)

In [44]:
frame['price']

0    1.2
1    1.0
2    0.6
3    0.9
4    1.7
Name: price, dtype: float64

In [45]:
frame.loc[2:4]

    color  object  price
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [46]:
frame.loc[[2,4]]

    color  object  price
2  yellow  pencil    0.6
4   white     mug    1.7

In [47]:
frame[0:1]

  color object  price
0  blue   ball    1.2

In [48]:
frame[1:3]

    color  object  price
1   green     pen    1.0
2  yellow  pencil    0.6

In [49]:
frame['object'][3]

'paper'

### Assigning Values

In [50]:
frame.index.name = 'id'
frame.columns.name = 'item'
frame

item   color  object  price
id
0       blue    ball    1.2
1      green     pen    1.0
2     yellow  pencil    0.6
3        red   paper    0.9
4      white     mug    1.7

In [51]:
frame['new'] = 12
frame

item   color  object  price  new
id
0       blue    ball    1.2   12
1      green     pen    1.0   12
2     yellow  pencil    0.6   12
3        red   paper    0.9   12
4      white     mug    1.7   12

In [52]:
frame['new'] = [3.0,1.3,2.2,0.8,1.1]
frame

item   color  object  price  new
id
0       blue    ball    1.2  3.0
1      green     pen    1.0  1.3
2     yellow  pencil    0.6  2.2
3        red   paper    0.9  0.8
4      white     mug    1.7  1.1

In [53]:
frame.loc[2, 'price'] = 10.0
frame

item   color  object  price  new
id
0       blue    ball    1.2  3.0
1      green     pen    1.0  1.3
2     yellow  pencil   10.0  2.2
3        red   paper    0.9  0.8
4      white     mug    1.7  1.1

### Updating an Entire Column in a DataFrame
* We can update all the values of a column at once.
* One way is to use np.arange(), which generates a sequence of numbers.
* The generated sequence is assigned to a DataFrame column.

In [54]:
ser = pd.Series(np.arange(6))
ser

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [55]:
frame['new'] = ser
frame

item   color  object  price  new
id
0       blue    ball    1.2    0
1      green     pen    1.0    1
2     yellow  pencil   10.0    2
3        red   paper    0.9    3
4      white     mug    1.7    4

In [56]:
frame.loc[5] = ['cyan' , 'duster' , 2.5,7]
frame

item   color  object  price  new
id
0       blue    ball    1.2    0
1      green     pen    1.0    1
2     yellow  pencil   10.0    2
3        red   paper    0.9    3
4      white     mug    1.7    4
5       cyan  duster    2.5    7

In [57]:
frame.loc[2, 'price'] = 3.3
frame

item   color  object  price  new
id
0       blue    ball    1.2    0
1      green     pen    1.0    1
2     yellow  pencil    3.3    2
3        red   paper    0.9    3
4      white     mug    1.7    4
5       cyan  duster    2.5    7

### Membership of a Value

In [58]:
frame.isin([1.0,'pen'])
frame

item   color  object  price  new
id
0       blue    ball    1.2    0
1      green     pen    1.0    1
2     yellow  pencil    3.3    2
3        red   paper    0.9    3
4      white     mug    1.7    4
5       cyan  duster    2.5    7

### Deleting a Column

In [59]:
del frame['new']
frame

item   color  object  price
id
0       blue    ball    1.2
1      green     pen    1.0
2     yellow  pencil    3.3
3        red   paper    0.9
4      white     mug    1.7
5       cyan  duster    2.5

### Filtering

In [60]:
frame[frame['price'] <= 1.2 ]

item  color object  price
id
0      blue   ball    1.2
1     green    pen    1.0
3       red  paper    0.9

### DataFrame from Nested dict

In [61]:
nestdict = { 'red': { 2012: 22, 2013: 33 },
'white': { 2011: 13, 2012: 22, 2013: 16},
'blue': {2011: 17, 2012: 27, 2013: 18}}

In [62]:
nestdict

{'red': {2012: 22, 2013: 33},
 'white': {2011: 13, 2012: 22, 2013: 16},
 'blue': {2011: 17, 2012: 27, 2013: 18}}

In [63]:
frame2  = pd.DataFrame(nestdict)
frame2

       red  white  blue
2012  22.0     22    27
2013  33.0     16    18
2011   NaN     13    17

* Transposition means interchanging the rows and columns of a DataFrame. It is similar to the transpose operation in matrices.

In [65]:
frame2.T

       2012  2013  2011
red    22.0  33.0   NaN
white  22.0  16.0  13.0
blue   27.0  18.0  17.0

In [66]:
frame2.transpose()

       2012  2013  2011
red    22.0  33.0   NaN
white  22.0  16.0  13.0
blue   27.0  18.0  17.0

### Index Objects in Pandas
An Index object in Pandas is an immutable (cannot be changed)
sequence of labels used to identify the rows or columns of a
Series or DataFrame.

In [68]:
ser = pd.Series([5,0,3,8,4], index=['red','blue','yellow','white','green'])
ser.index

Index(['red', 'blue', 'yellow', 'white', 'green'], dtype='str')

idxmin()
* Returns the index of the minimum value.

idxmax()
* Returns the index of the maximum value.

In [69]:
ser.idxmin()

'blue'

In [70]:
ser.idxmax()

'white'

* In Pandas, index labels do not have to be unique. A Series or DataFrame can have duplicate index labels.

In [71]:
serd = pd.Series(range(6), index=['white', 'white','blue','green',
'green','yellow'])

serd

white     0
white     1
blue      2
green     3
green     4
yellow    5
dtype: int64

In [72]:
serd['white']

white    0
white    1
dtype: int64

* Checks if Index is Unique

In [73]:
serd.index.is_unique

False

In [74]:
frame.index.is_unique

True

### Arithematic Methods in Pandas
Pandas provides arithmetic methods to perform mathematical operations on Series and DataFrame objects. These methods automatically align data based on index and column labels and can handle missing values using the fill_value parameter.

In [75]:
frame1 = pd.DataFrame(np.arange(16).reshape((4,4)),
index=['red','blue','yellow','white'],
columns=['ball','pen','pencil', 'paper' ])

frame1

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [76]:
frame2= pd.DataFrame(np.arange(12).reshape((4,3)),
index=['blue','green','white','yellow'],
columns=['mug','pen','ball'])

frame2

        mug  pen  ball
blue      0    1     2
green     3    4     5
white     6    7     8
yellow    9   10    11

In [77]:
frame1.add(frame2)

        ball  mug  paper   pen  pencil
blue     6.0  NaN    NaN   6.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   20.0  NaN    NaN  20.0     NaN
yellow  19.0  NaN    NaN  19.0     NaN

In [78]:
frame1.mul(frame2)

        ball  mug  paper   pen  pencil
blue     8.0  NaN    NaN   5.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   96.0  NaN    NaN  91.0     NaN
yellow  88.0  NaN    NaN  90.0     NaN

### Operations Between DataFrame and Series

* when you perform an operation between a DataFrame and a Series, Pandas aligns the Series index with the DataFrame columns (by default).

In [79]:
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
index=['red','blue','yellow','white'],
columns=['ball','pen','pencil', 'paper'])

frame

        ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [80]:
ser = pd.Series(np.arange(4), index=['ball','pen','pencil', 'paper'])
ser

ball      0
pen       1
pencil    2
paper     3
dtype: int64

In [81]:
frame - ser

        ball  pen  pencil  paper
red        0    0       0      0
blue       4    4       4      4
yellow     8    8       8      8
white     12   12      12     12

* Pandas matches the Series labels with the column names. It subtracts the Series from every row.

In [82]:
ser - frame

        ball  pen  pencil  paper
red        0    0       0      0
blue      -4   -4      -4     -4
yellow    -8   -8      -8     -8
white    -12  -12     -12    -12

* Each value in the Series is subtracted by the corresponding DataFrame value.

In [83]:
ser['mug'] = 9
ser

ball      0
pen       1
pencil    2
paper     3
mug       9
dtype: int64

In [84]:
frame - ser

        ball  mug  paper  pen  pencil
red        0  NaN      0    0       0
blue       4  NaN      4    4       4
yellow     8  NaN      8    8       8
white     12  NaN     12   12      12

* There is no DataFrame value for mug, so it is treated as missing

### Function Application and Mapping

1. Functions by Element (Universal Functions - ufuncs)

A universal function (ufunc) is a NumPy function that operates on each element individually

Pandas provides methods to apply functions to data in a Series or DataFrame. The most commonly used methods are:

* apply()
* applymap() (deprecated in newer versions; use map() for Series or other alternatives for DataFrames)
* map()